FROM node

RUN mkdir -p /srv/frontend

RUN chown node: /srv/frontend

COPY selfservicetool/frontend /srv/frontend

WORKDIR /srv/frontend

USER node

RUN npm ci && npm cache clean --force

ENTRYPOINT npm start
