name: CI-frontend
run-name: ${{ github.actor }} will sehen, ob die CI-Pipeline geht
on: 
  push:
    branches:
      - '*'
jobs:
  webfrontend:
    runs-on: ubuntu-latest
    steps:
#hier ist das Template für das Frontend. Da Adrian immer neue Branches verwendet, steht als Branch im Moment Main, der muss halt auf den neuen Branch geändert werden. Dockerfile sollte aber nicht angepasst werden müssen
       - uses: actions/checkout@v2
         with:
           ref: main   # <----- Hier anpassen
       - run: printf "FROM node\nRUN mkdir -p /srv/frontend\nRUN chown node: /srv/frontend\nCOPY selfservicetool/frontend /srv/frontend\nWORKDIR /srv/frontend\nUSER node\nRUN npm ci && npm cache clean --force\nENTRYPOINT npm start\n" > ../Dockerfile
       - run: docker build .. -t frontend
