name: CI
run-name: ${{ github.actor }} will sehen, ob die CI-Pipeline geht
on: 
  push:
    branches:
      - '*'
jobs:
  webfrontend:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/lamasmithueten/selfservicetool.git
      - run: cd selfservicetool
      - run: git checkout devops
      - run: cd ..
      - run: mkdir frontend
      - run: cd frontend 
      - run: git clone https://github.com/lamasmithueten/selfservicetool.git
      - run: cd ..
      - run: cp ../selfservicetool/devops/frontend/dockerfile .
      - run: docker build . -t frontend
      - run: cd backend
      - run: git clone https://github.com/lamasmithueten/selfservicetool.git
      - run: cd ..
      - run: cp ../selfservicetool/devops/backend/dockerfile .
      - run: docker build . -t api
