name: CI
run-name: ${{ github.actor }} will sehen, ob die CI-Pipeline geht
on: 
  push:
    branches:
      - '*'
jobs:
  webfrontend:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - run: ls -la 
       - run: pwd
       - run: tree 
       - run: printf "FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build\n\nWORKDIR /source\n\nCOPY selfservicetool/sstWebAPI/*.sln .\nCOPY selfservicetool/sstWebAPI/sstWebAPI/*.csproj ./sstWebAPI/\nRUN dotnet restore\n\nCOPY selfservicetool/sstWebAPI/. ./sstWebAPI/\nWORKDIR /source/sstWebAPI\nRUN dotnet restore\nRUN dotnet publish -c release -o /app --no-restore\n\nFROM mcr.microsoft.com/dotnet/aspnet:8.0\nWORKDIR /app\nCOPY --from=build /app ./\n\nRUN sed -i 's/server=localhost/server=database/g' /app/appsettings.json\n\nENTRYPOINT [\"dotnet\", \"sstWebAPI.dll\"]\n" > ../Dockerfile
       - run: docker build .. -t backend 

       - uses: actions/checkout@v2
         with:
           ref: backend
       - run: ls -la 
       - run: pwd
       - run: tree 
