name: CI
run-name: ${{ github.actor }} will sehen, ob die CI-Pipeline geht
on: 
  push:
    branches:
      - '*'
jobs:
  webfrontend:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - run: ls -la 
       - run: pwd
       - run: tree 
       - uses: actions/checkout@v2
         with:
           ref: backend
       - run: ls -la 
       - run: pwd
       - run: tree 
