name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  webfrontend:
    runs-on: debian-12
    steps:
      - run: sed -i 's/apache2/httpd/g' /var/www/html

