name: selfservicetool
run-name: ${{ github.actor }} fragt sich warum in der Demo so viele Emojis gespammt werden
on: 
  push:
    branches:
      - main
jobs:
  webfrontend:
    runs-on: self-hosted
    steps:
      - run: echo $USER
      - run: sed -i 's/httpd/apache2/g' /webserver/selfservicetool/index.html
      - run: echo lul
