name: selfservicetool
run-name: ${{ github.actor }} fragt sich warum in der Demo so viele Emojis gespammt werden
on: 
  push:
    branches:
      - main
jobs:
  webfrontend:
    runs-on: self-hosted
    steps:
#      - run: docker compose -f /home/git/docker-compose.yml down
#      - run: docker-compose -f /home/git/docker-compose.yml build
#      - run: docker compose -f /home/git/docker-compose.yml up -d
       - run: if [[ $(docker ps | awk 'NR!=1' | wc -l) -gt 0 ]] then docker stop $(docker ps -q) && docker rm $(docker ps -aq); fi
       - run: docker run -dp 80:80 --name webfrontend nginx
       - run: docker run -dp 3306:3306 -e MYSQL_ROOT_PASSWORD=linux -v mysql:/var/lib/mysql --name database mariadb
