name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  webfrontend:
    runs-on: self-hosted
    steps:
      - run: echo $USER
      - run: sed -i 's/apache2/httpd/g' /webserver/selfservicetool/index.html

