name: selfservicetool
run-name: ${{ github.actor }} fragt sich warum in der Demo so viele Emojis gespammt werden
on: 
  push:
    branches:
      - main
jobs:
  webfrontend:
    runs-on: self-hosted
    steps:
      - run: sh -c "docker stop $(docker ps -aq) && docker rm $(docker ps -aq)"
      - run: docker run -dp 80:80 nginx
      - run: docker run -dp 3306:3306 -v mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=linux mariadb
      - run: env
